--Tabla del encabezado
CREATE TABLE CAB_FORMULARIO(
IDCABECERA INT PRIMARY KEY NOT NULL,
NOMOFICINA VARCHAR(20) NOT NULL,
IDPROVINCIAFK INT REFERENCES PROVINCIAS(IDPROVINCIA),
ACTA NUMERIC(13,0) NOT NULL,
NHIJOS NUMERIC(2,0),
FREGISTRO timestamp default current_timestamp NOT NULL
);

create sequence IDCABECERA MINVALUE 0 START WITH 0 cache 2;
select * from persona
CREATE TABLE PERSONA(
IDPERSONA INT PRIMARY KEY NOT NULL,
NOMBRES VARCHAR(20) NOT NULL,
APELLIDOS VARCHAR(20) NOT NULL,
IDNACIONALIDADFK INT REFERENCES NACIONALIDAD(IDNACIONALIDAD),
CEDULA NUMERIC(10,0) NOT NULL,
FNACIMIENTO DATE NOT NULL,
EDADCASADOS NUMERIC(2,0) NOT NULL,
NMATRIMONIOS NUMERIC(2,0) NOT NULL,
IDESTADOFK INT REFERENCES ESTADOCIVIL(IDESTADO),
IDETNIAFK INT REFERENCES ETNIA(IDETNIA),
IDINSTRUCCIONFK INT REFERENCES NIVELINSTRUCCION(IDINSTRUCCION),
IDPROVINCIAFK REFERENCES PROVINCIAS(IDPROVINCIA),
LOCALIDAD VARCHAR(75) NOT NULL
);

create sequence IDPERSONA MINVALUE 0 START WITH 0 cache 2;
drop sequence idpersona
INSERT INTO PERSONA VALUES (IDPERSONA.NEXTVAL,1,'AARON DAVID', 'CRUZ RAMIREZ',1,1725661027,'15-05-1996',5,0,1,6,8,17,'CARLOS MANTILLA Y TOLEDO');
INSERT INTO PERSONA VALUES (idpersona.nextval,'Aaron David', 'cruz ramirez'  ,1  ,1725661027  ,'15-05-1996'  ,5  ,0 ,1  ,6  ,8  ,17  ,'san jose'  );
select IDCABECERA from cab_formulario where ACTA = '123456'

CREATE TABLE NIVELINSTRUCCION(
IDINSTRUCCION INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(30) NOT NULL
);
CREATE SEQUENCE IDINSTRUCCION MINVALUE 0 START WITH 0 CACHE 10;

INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'NINGUNO');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'CENTRO DE ALFABETIZACION');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'PRIMARIA');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'SECUNDARIA');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'EDUCACIÓN BÁSICA');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'EDUCACIÓN MEDIA');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'CICLO POSBACHILLERATO');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'SUPERIOR');
INSERT INTO NIVELINSTRUCCION VALUES (IDINSTRUCCION.NEXTVAL,'POSGRADO');

CREATE TABLE NACIONALIDAD(
IDNACIONALIDAD INT PRIMARY KEY NOT NULL,
TIPONAC VARCHAR(20) NOT NULL
);
CREATE SEQUENCE IDNACIONALIDAD MINVALUE 0 START WITH 0 CACHE 3;

INSERT INTO NACIONALIDAD  VALUES (IDNACIONALIDAD.nextval, 'ECUATORIANA');
INSERT INTO NACIONALIDAD  VALUES (IDNACIONALIDAD.nextval, 'EXTRANJERO');
INSERT INTO NACIONALIDAD  VALUES (IDNACIONALIDAD.nextval, 'OTRO');

CREATE TABLE ESTADOCIVIL(
IDESTADO INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL
);
CREATE SEQUENCE IDESTADO MINVALUE 0 START WITH 0 CACHE 8;

INSERT INTO ESTADOCIVIL  VALUES (IDESTADO.nextval, 'SOLTERO');
INSERT INTO ESTADOCIVIL  VALUES (IDESTADO.nextval, 'DIVORCIADO');
INSERT INTO ESTADOCIVIL  VALUES (IDESTADO.nextval, 'VIUDO');

CREATE TABLE ETNIA(
	IDETNIA INT  PRIMARY KEY NOT NULL,
	TIPO VARCHAR(20)
);

CREATE SEQUENCE IDETNIA MINVALUE 0 START WITH 0 CACHE 8;

INSERT INTO ETNIA  VALUES (IDETNIA.nextval, 'INDÍGENA');
INSERT INTO ETNIA  VALUES (IDETNIA.nextval,'AFROECUATORIANO');
INSERT INTO ETNIA VALUES (IDETNIA.NEXTVAL,'NEGRO');
INSERT INTO ETNIA VALUES (IDETNIA.NEXTVAL,'MULATO');
INSERT INTO ETNIA  VALUES (IDETNIA.NEXTVAL,'MONTUBIO');
INSERT INTO ETNIA  VALUES (IDETNIA.NEXTVAL,'MESTIZO');
INSERT INTO ETNIA  VALUES (IDETNIA.NEXTVAL,'BLANCO');
INSERT INTO ETNIA  VALUES (IDETNIA.NEXTVAL,'OTRO');

SELECT * FROM ETNIA

CREATE TABLE PROVINCIAS(
IDPROVINCIA INT PRIMARY KEY,
PROVINCIA VARCHAR(40)
);
CREATE SEQUENCE IDPROVINCIA MINVALUE 0 START WITH 0 CACHE 25;

INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'AZUAY');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'BOLIVAR');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'CAÑAR');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'CARCHI');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'COTOPAXI');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'CHIMBORAZO');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'EL ORO');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'ESMERALDAS');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'GUAYAS');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'IMBABURA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'LOJA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'LOS RIOS');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'MANABÍ');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'MORONA SANTIAGO');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'NAPO');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'PASTAZA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'PICHINCHA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'TUNGURAHUA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'ZAMORA CHINCHIPE');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'GALÁPAGOS');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'SUCUMBIOS');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'ORELLANA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'SANTO DOMINGO DE LOS TSÁCHILAS');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'SANTA ELENA');
INSERT INTO PROVINCIAS VALUES (IDPROVINCIA.NEXTVAL,'NO DELIMITADO');

SELECT * FROM PROVINCIAS

CREATE TABLE CANTONES(
IDCANTON INT PRIMARY KEY,
IDPROVINCIAFK INT REFERENCES PROVINCIAS(IDPROVINCIA),
CANTON VARCHAR(40)
);
CREATE SEQUENCE IDCANTON MINVALUE 0 START WITH 50 CACHE 200;

SELECT * FROM CANTONES

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'CUENCA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'GIRÓN');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'GUALACEO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'NABÓN');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'PAUTE');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'PUCARÁ');
INSERT INTO CANTONES VALUES (7, 1,'SAN FERNANDO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'SANTA ISABEL');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'SIGSIG');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'OÑA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'CHORDELEG');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'EL PAN');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'SEVILLA DE ORO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'GUACHAPALA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 1,'CAMILO PONCE ENRÍQUEZ');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'GUARANDA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'CALUMA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'CHILLANES');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'CHIMBO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'ECHEANDÍA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'LAS NAVES');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 2,'SAN MIGUEL');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 3,'AZOGUES');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,3,'BIBLIÁN');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,3,'CAÑAR');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,3,'LA TRONCAL');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,3,'EL TAMBO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,3,'DELEG');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,3,'SUSCAL');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 4,'TULCAN');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 5,'RIOBAMBA');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,6,'LATACUNGA');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL,7,'MACHALA');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 8,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 9,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 10,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 11,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 12,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 13,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 14,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 15,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 16,'');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'QUITO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'CAYAMBE');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'MEJÍA');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'PEDRO MONCAYO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'RUMIÑAHUI');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'SAN MIGUEL DE LOS BANCOS');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'PEDRO VICENTE MALDONADO');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 17,'PUERTO QUITO');

INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 18,'');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 19,'');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 20,'');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 21,'');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 22,'');

INSERT INTO CANTONES  VALUES (IDCANTON.NEXTVAL, 23,'SANTO DOMINGO DE LOS COLORADOS');
INSERT INTO CANTONES  VALUES (IDCANTON.NEXTVAL,23,'LA CONCORDIA');

INSERT INTO CANTONES  VALUES (IDCANTON.NEXTVAL, 24,'SANTA ELENA');
INSERT INTO CANTONES  VALUES (IDCANTON.NEXTVAL, 24,'LA LIBERTAD');
INSERT INTO CANTONES VALUES (IDCANTON.NEXTVAL, 24,'SALINAS');


CREATE TABLE PARROQUIAS(
IDPARROQUIA INT PRIMARY KEY,
IDCANTONFK INT REFERENCES CANTONES(IDCANTON),
NOMPARROQUI VARCHAR(40)
);
CREATE SEQUENCE IDPARROQUIA MINVALUE 0 START WITH 0 CACHE 100;

INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'BELISARIO QUEVEDO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CARCELÉN');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CENTRO HISTÓRICO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'COCHAPAMBA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'COMITÉ DEL PUEBLO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'COTOCOLLAO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CHILIBULO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CHILLOGALLO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CHIMBACALLE');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'EL CONDADO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'GUAMANÍ');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'IÑAQUITO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'ITCHIMBIA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'JIPIJAPA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'KENNEDY');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA ARGELIA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA CONCEPCIÓN');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA ECUATORIANA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA FERROVIARIA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA LIBERTAD');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA MAGDALENA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA MENA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'MARISCAL SUCRE');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PONCEANO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PUENGASÍ');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'QUITUMBE');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'RUMIPAMBA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'SAN BARTOLO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'SAN ISIDRO DEL INCA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'SAN JUAN');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'SOLANDA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'TURUBAMBA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'ALANGASÍ');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'AMAGUAÑA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'ATAHUALPA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CALACALÍ');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CALDERON');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CONOCOTO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CUMBAYÁ');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CHAVEZPAMBA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'CHECA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'EL QUINCHE');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'GUALEA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'GUANGOPOLO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'GUAYLLABAMBA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LA MERCED');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LLANO CHICO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'LLOA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'MINDO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'NANEGAL');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'NANEGALITO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'NAYÓN');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'NONO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PACTO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PERUCHO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PIFO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PÍNTAG');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'POMASQUI');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PUÉLLARO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'PUEMBO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'SAN ANTONIO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'SAN JOSÉ DE SALINAS');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'TABELA');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'TUMBACO');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'YARUQUÍ');
INSERT INTO PARROQUIAS VALUES (IDPARROQUIA.NEXTVAL, 43,'ZÁMBIZA');

select idcanton, canton from provincias r, cantones u 
where r.idprovincia = u.idprovinciafk and idprovincia = 17

select  * from cab_formulario